MODEL:
  # Custom Meta_ARCH that defines a classification cnn
  META_ARCHITECTURE: "FeatureExtractor"
  BACKBONE:
  # This backbone is based on Resnet-FPN architecture with modifications,
  # - Each Resnet block is composed of only one Bottleneck (3 conv + shortcut)
  # - The width of each layer is 4x less than the original implementation
  # - The Stem block has an ouput_stride of 2 (instead of 4)
  # The idea is to emphasize local features in higher features maps rather than
  # global features in lower features maps (to detect small objects).
    NAME: "build_simple_resnet_backbone" # custom simple resnet
    # Freeze the first several stages so they are not trained.
    # There are 5 stages in ResNet. The first is a convolution, and the following
    # stages are each group of residual blocks.
    FREEZE_AT: 0 # 0: no freeze, n>=1: freeze up to the n-th block
    NUM_CLASSES: 2 # defective and intact pieces
    CLASSIFIER: "linear" #the classifier layer name
  RESNETS:
    DEPTH: 14 # there are 14 layers in our simple Resnet   
    OUT_FEATURES: ["linear"] #see BACKBONE.CLASSIFIER
    # Number of groups to use; 1 ==> ResNet; > 1 ==> ResNeXt
    NUM_GROUPS: 1
    # Options: FrozenBN, GN, "SyncBN", "BN"
    NORM: "BN" # "FrozenBN"
    # Baseline width of each group.
    # Scaling this parameters will scale the width of all bottleneck layers.
    WIDTH_PER_GROUP: 16 # initially 64
    # Place the stride 2 conv on the 1x1 filter
    # Use True only for the original MSRA ResNet; use False for C2 and Torch models
    STRIDE_IN_1X1: True
    # Apply dilation in stage "res5"
    RES5_DILATION: 1
    # Output width of res2. Scaling this parameters will scale the width of all 1x1 convs in ResNet
    # For R18 and R34, this needs to be set to 64
    RES2_OUT_CHANNELS: 64 # initially 256
    STEM_OUT_CHANNELS: 16 # initially 64
    # Apply Deformable Convolution in stages
    # Specify if apply deform_conv on Res2, Res3, Res4, Res5
    DEFORM_ON_PER_STAGE: [False, False, False, False]
    # Use True to use modulated deform_conv (DeformableV2, https://arxiv.org/abs/1811.11168);
    # Use False for DeformableV1.
    DEFORM_MODULATED: False
    # Number of groups in deformable conv.
    DEFORM_NUM_GROUPS: 1
DATASETS:
  TRAIN: ("xris_fal_syn_train",)
  TEST: ("xris_fal_syn_val",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 1
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (30000, 60000)
  MAX_ITER: 90000
TEST:
  EVAL_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (320, 352, 384, 416,) # (640, 672, 704, 736, 768, 800)
VERSION: 2
# Directory where output files are written
OUTPUT_DIR: "./output"
